{{ if .Values.replication }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmredis-slave
  namepace: fleet-helm-example
spec:
  replicas: 2
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
{{ end }}
